asset:
  root: "assets/object"
  category: 'lighter'
  input_dir: ${.root}/${.category}
  instance_id: '000'
  scale_factor: 1.0

generation:
  batch_size_outer: 512
  batch_size_inner: 512
  contact_score_threshold: 0.5
  target_n_result: 1000

digits:
  sharpa:
    n_contact: 4
    movable_links: ["left_thumb_DP", "left_index_DP", "left_middle_DP", "left_ring_DP"]
    specific_links: ["left_thumb_DP"]
    static_links: ["left_hand_C_MC"]
    fixed_zero_joints: ["left_pinky_CMC", "left_pinky_DIP", "left_pinky_PIP", "left_pinky_MCP_FE"]
    movable_disabled_normal: [[[-1.0, 0.0, 0.0], 0.0]]
    static_allowed_normal: [[1.0, 0.0, 0.0], 0.25]
    override_disabled_normal:
      left_thumb_DP:
        - [[0.0, -1.0, 0.0], 0.49999]
    additional_filter_rules:
      - link_name_contains: ["thumb"]
        centroid_min:
          x: 0.02
          y: -0.002
      - link_name_contains: ["index", "ring", "pinky"]
        centroid_min:
          x: 0.008
      - link_name_contains: ["middle"]
        centroid_min:
          x: 0.01
          y: -0.002
          z: -0.005
        centroid_max:
          x: 0.02
          z: 0.005
  wuji:
    n_contact: 4
    movable_links: ["finger1_tip_link", "finger2_tip_link", "finger3_tip_link", "finger4_tip_link"]
    specific_links: ["finger1_tip_link"]
    static_links: ["palm_link"]
    fixed_zero_joints: ["finger5_joint1", "finger5_joint3", "finger5_joint4"]
    movable_disabled_normal: [[[-1.0, 0.0, 0.0], 0.4]]
    static_allowed_normal: [[1.0, 0.0, 0.0], 0.25]
    override_disabled_normal: {}

parts:
  sample_weights:
    green: 0.15
    red: 0.4
    blue: 0.15
    white: 0.15
    black: 0.15
  centroid_sample_scale:
    green: 0.8
    blue: 0.8
    white: 0.5
    black: 0.5
  robot_rules:
    sharpa:
      touchable_area:
        left_thumb_DP: ['green']
        left_index_DP: ['white','black']
        left_middle_DP: ['blue']
        left_ring_DP: ['white','black']
      exclusive_touchable_area: True
      forbidden_area:
        left_thumb_DP: ['white', 'black', 'blue', 'red']
        left_index_DP: ['blue', 'green', 'red']
        left_middle_DP: ['white', 'black', 'green', 'red']
        left_ring_DP: ['blue', 'green', 'red']
    wuji:
      touchable_area:
        finger1_tip_link: ['green']
        finger2_tip_link: ['white','black']
        finger3_tip_link: ['blue']
        finger4_tip_link: ['white','black']
      exclusive_touchable_area: True
      forbidden_area:
        finger1_tip_link: ['white', 'black', 'blue', 'red']
        finger2_tip_link: ['blue', 'green', 'red']
        finger3_tip_link: ['white', 'black', 'green', 'red']
        finger4_tip_link: ['blue', 'green', 'red']
